### ISSUE TITLE
ClaymoreCharge path displayed in decision does not match resolution

### ISSUE THREAD

**Issue by readmaniak** [Zheneq/hc#32] opened 2023-02-05 10:05 UTC
Oceanus-3 server, build 0.7.1.1 beta. Game 2023_02_05__09_36_24. Decision phase shown garrison getting damaged

**Comment by Zheneq** [comment] 2023-02-05 12:45
Probably related to other dash issues caused by lancers' positions not updating properly.

**Comment by Zheneq** [comment] 2024-01-27 11:37
fixed in https://github.com/Zheneq/hc/releases/tag/0.7.5

**Closed as completed by Zheneq** 2024-01-27 11:37 UTC
Labels: bug-specific
